export const createClientsSection = () => {
  const section = document.createElement('section')
  const h1 = document.createElement('h1')
  const container = document.createElement('div')
  const main = document.createElement('main')
  const sortingDisplay = document.createElement('thead')
  const theadTr = document.createElement('tr')
  const sortingDisplayId = document.createElement('td')
  const sortingDisplayName = document.createElement('td')
  const sortingDisplayCreate = document.createElement('td')
  const sortingDisplayEdit = document.createElement('td')
  const sortingDisplayContacts = document.createElement('td')
  const sortingDisplayActions = document.createElement('td')
  const sortingDisplaySpan = document.createElement('span')
  const addUserBtn = document.createElement('button')
  const addUserBtnSvg = document.createElement('span')
  const tableWrapper = document.createElement('div')
  const clientsTable = document.createElement('table')
  const tbody = document.createElement('tbody')
  const createSpan = document.createElement('span')
  const editSpan = document.createElement('span')
}
